# App runner configuration
server.port=7070

# Database connection (used by infrastructure adapters)
db.url=jdbc:sqlite:helpdesk.db
db.driver=org.sqlite.JDBC
db.username=
db.password=

# Hibernate defaults
hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=false
hibernate.format_sql=true
